### ISSUE TITLE
Click seems incompatible with Python's IDLE (on Windows)

### ISSUE THREAD

**Issue by doobeh** [pallets/click#1021]
Open up IDLE (`python -m idlelib.idle`) and enter the following code:

```
import click

@click.command()
def hello():
    click.echo('Hello World!')


if __name__ == '__main__':
    hello()
```

Then save, and hit F5 to run-- gives the following error:

```
Traceback (most recent call last):
  File "C:\Users\username\Desktop\idler.py", line 9, in <module>
    hello()
  File "C:\Users\username\Environments\idler\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\username\Environments\idler\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\username\Environments\idler\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\username\Environments\idler\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\username\Desktop\idler.py", line 5, in hello
    click.echo('Hello World!')
  File "C:\Users\username\Environments\idler\lib\site-packages\click\utils.py", line 217, in echo
    file = _default_text_stdout()
  File "C:\Users\username\Environments\idler\lib\site-packages\click\_compat.py", line 621, in func
    rv = wrapper_func()
  File "C:\Users\username\Environments\idler\lib\site-packages\click\_compat.py", line 385, in get_text_stdout
    rv = _get_windows_console_stream(sys.stdout, encoding, errors)
  File "C:\Users\username\Environments\idler\lib\site-packages\click\_winconsole.py", line 261, in _get_windows_console_stream
    func = _stream_factories.get(f.fileno())
io.UnsupportedOperation: fileno
```

OSX Works fine.  Seems like same avenue as https://github.com/pallets/click/issues/770

**Comment by davidism** [comment]
Seems to be fixed now. 7.1 will be out soon with the merged PR.
