### ISSUE TITLE
Click breaks PDB

### ISSUE THREAD

**Issue by timka** [pallets/click#1121]
When I add `set_trace()` in my code the interpreter quits.
```
(Pdb++)
Traceback (most recent call last):
  File "generate.py", line 554, in <module>
    cli(standalone_mode=False)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "generate.py", line 508, in cli
    schema, registry, base_dir, source_base_dir, types_dir, types_templates_dir
  File "generate.py", line 358, in generate_types
    touched_files = set()
  File "generate.py", line 358, in generate_types
    touched_files = set()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/bdb.py", line 51, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/bdb.py", line 70, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
```

Tried calling my click command with and without `standalone_mode=False`, same result. I think this may have something to do with #138

**Comment by timka** [comment]
My workaround is to call `set_trace()` before main CLI callable:

```
if __name__ == "__main__":
    from pdb import set_trace; set_trace()
    cli()
```

**Comment by robintully** [comment]
can you provide an example? Running on click 7 with python 3.7 this successfully enters the debugger `import click

@click.command()
def debug():
    import pdb; pdb.set_trace(

if __name__ == '__main__':
    debug()`

**Comment by robintully** [comment]
can you provide an example? Running on click 7 with python 3.7 this successfully enters the debugger `
`
import click

@click.command()
def debug():
    import pdb; pdb.set_trace(

if __name__ == '__main__':
    debug()
`

**Comment by robintully** [comment]
can you provide an example? with python 3.7 and click 7 this code sample enters the debugger
```
import click

@click.command()
def debug():
    import pdb; pdb.set_trace(

if __name__ == '__main__':
    debug()
```

**Comment by jcrotts** [comment]
Closing this because it seems to be working in click 7, please reopen if you have an issue.
