### ISSUE TITLE
TypeError: Arguments take exactly one parameter declaration, got 2

### ISSUE THREAD

**Issue by Benjamin-Lee** [pallets/click#1128]
Updating from Click 6 to 7 appears to break on this option:

    @click.option("-o", '--output', type=click.Path(exists=False, dir_okay=False), default="freqgen.html", help="The path to the output HTML file. Defaults to freqgen.html.")

The traceback is:

```
Benjamins-MacBook-Pro-5:examples BenjaminLee$ freqgen visualize --help
Traceback (most recent call last):
  File "/Users/BenjaminLee/Desktop/Python/Research/freqgen/env/bin/freqgen", line 11, in <module>
    load_entry_point('freqgen', 'console_scripts', 'freqgen')()
  File "/Users/BenjaminLee/Desktop/Python/Research/freqgen/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/BenjaminLee/Desktop/Python/Research/freqgen/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/Users/BenjaminLee/Desktop/Python/Research/freqgen/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/Users/BenjaminLee/Desktop/Python/Research/freqgen/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/BenjaminLee/Desktop/Python/Research/freqgen/freqgen/freqgen/cli.py", line 23, in <module>
    @click.option("-o", '--output', type=click.Path(exists=False, dir_okay=False), help="The output YAML file.")
  File "/Users/BenjaminLee/Desktop/Python/Research/freqgen/env/lib/python3.6/site-packages/click/decorators.py", line 151, in decorator
    _param_memo(f, ArgumentClass(param_decls, **attrs))
  File "/Users/BenjaminLee/Desktop/Python/Research/freqgen/env/lib/python3.6/site-packages/click/core.py", line 1808, in __init__
    Parameter.__init__(self, param_decls, required=required, **attrs)
  File "/Users/BenjaminLee/Desktop/Python/Research/freqgen/env/lib/python3.6/site-packages/click/core.py", line 1338, in __init__
    self._parse_decls(param_decls or (), expose_value)
  File "/Users/BenjaminLee/Desktop/Python/Research/freqgen/env/lib/python3.6/site-packages/click/core.py", line 1841, in _parse_decls
    'parameter declaration, got %d' % len(decls))
TypeError: Arguments take exactly one parameter declaration, got 2
```

**Comment by davidism** [comment]
I can't reproduce this issue with the information given.. This error will happen on `@click.argument` when more than one name is supplied, but `@click.option` continues to work as expected.

**Comment by Benjamin-Lee** [comment]
This error also seems to be happening here, also related to the upgrade from 6 to 7:

https://github.com/tmux-python/tmuxp/issues/433

**Comment by Benjamin-Lee** [comment]
What I can't wrap my head around is why a `@click.option` is generating an error for `@click.argument`

**Comment by davidism** [comment]
It's not, only `click.argument` generates that error. As I said, with the limited information given, I couldn't reproduce your issue. `click.option` works as expected.

The issue you linked to was caused by an error in their `argument` definitions that Click 7 made explicit.
