### ISSUE TITLE
click.edit() expects editor to be executable with no args

### ISSUE THREAD

**Issue by kabniel** [pallets/click#119]
```
$ EDITOR='nano -L'
$ export EDITOR
```

```
>>> import click
>>> click.edit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "click/termui.py", line 409, in edit
    return editor.edit(text)
  File "click/_termui_impl.py", line 371, in edit
    self.edit_file(name)
  File "click/_termui_impl.py", line 348, in edit_file
    raise ClickException('%s: Editing failed: %s' % (editor, e))
click.exceptions.ClickException: nano -L: Editing failed: [Errno 2] No such file or directory
```

**Comment by dufferzafar** [comment]
Has this been fixed? I'm facing a similar issue when I try to use VS Code as my editor:

```pytb
>>> click.edit(editor='code-insiders -w')

/bin/sh: code-insiders -w: command not found

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/click/termui.py", line 587, in edit
    return editor.edit(text)
  File "/usr/lib/python3.8/site-packages/click/_termui_impl.py", line 497, in edit
    self.edit_file(name)
  File "/usr/lib/python3.8/site-packages/click/_termui_impl.py", line 472, in edit_file
    raise ClickException("{}: Editing failed!".format(editor))
click.exceptions.ClickException: code-insiders -w: Editing failed!
```
