### ISSUE TITLE
OSError on MinGW64 with MSYS2 on Windows 8.1

### ISSUE THREAD

**Issue by victorliu** [pallets/click#1338]
A most basic script containing:

    import click
    click.echo('run')

Produces the following stacktrace:

    Traceback (most recent call last):
      File "t.py", line 3, in <module>
        click.echo('run')
      File "C:/msys64/mingw64/lib/python3.7/site-packages\click\utils.py", line 260, in echo
        file.write(message)
      File "C:/msys64/mingw64/lib/python3.7/site-packages\click\_compat.py", line 630, in _safe_write
        return _write(s)
      File "C:/msys64/mingw64/lib/python3.7/site-packages\colorama\ansitowin32.py", line 41, in write
        self.__convertor.write(text)
      File "C:/msys64/mingw64/lib/python3.7/site-packages\colorama\ansitowin32.py", line 164, in write
        self.wrapped.write(text)
      File "C:/msys64/mingw64/lib/python3.7/site-packages\click\_winconsole.py", line 180, in write
        return self._text_stream.write(x)
      File "C:/msys64/mingw64/lib/python3.7/site-packages\click\_winconsole.py", line 164, in write
        raise OSError(self._get_error_message(GetLastError()))
    OSError: Windows error 1

I am running under a MinGW64 bash shell installed through MSYS2 on a Windows 8.1 machine. 
This is with Python 3.7, colorama 0.4.1, and Click 7.0, but the error goes back to 6.0, whereas it does not occur on 5.1. Python 2 does not exhibit the error.

**Comment by davidism** [comment]
None of MinGW, MSYS2, or Windows 8.1 are officially supported, but I'll leave this open for a while in case someone sees something.

**Comment by danyeaw** [comment]
I can reproduce this issue with MSYS2 in Windows 10 when trying to use black which depends on click.

**Comment by eine** [comment]
@davidism, is this fixed in master but not released yet?
