### ISSUE TITLE
Documentation should show how to nest *groups* inside each other

### ISSUE THREAD

**Issue by Julian** [pallets/click#1387]
Given:

```
@click.group()
def main():
    pass

@click.group()
def otherMain():
    pass

@otherMain.command()
def otherMainSubcommand():
    pass
```

the docs should show how to add `otherMain` to `main` such that you can invoke e.g. `... otherMain otherMainSubcommand`.

What I can find is the [basic docs on creating groups](https://click.palletsprojects.com/en/7.x/quickstart/#nesting-commands) and mention of how to create nesting at the [*same* level via CommandCollection](https://click.palletsprojects.com/en/7.x/api/#click.CommandCollection), but not how to nest them at *different* levels as above.

The other somewhat suspicious looking thing is the [docstring for `Group.group`](https://click.palletsprojects.com/en/7.x/api/#click.Group.group), which was the next thing I found. It *looks* like this might have been what I want, but using it doesn't actually "work" on the above, it produces:

```
⊙  venv/bin/venvs --help                                                                                                                                              julian@Air ●
Traceback (most recent call last):
  File "venv/bin/venvs", line 11, in <module>
    load_entry_point('venvs', 'console_scripts', 'venvs')()
  File "/Users/julian/Development/venvs/venv/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/julian/Development/venvs/venv/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Users/julian/Development/venvs/venv/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Users/julian/Development/venvs/venv/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/julian/Development/venvs/venvs/_cli.py", line 14, in <module>
    main.group(name="find")(find.main)
  File "/Users/julian/Development/venvs/venv/site-packages/click/core.py", line 1246, in decorator
    cmd = group(*args, **kwargs)(f)
  File "/Users/julian/Development/venvs/venv/site-packages/click/decorators.py", line 115, in decorator
    cmd = _make_command(f, name, attrs, cls)
  File "/Users/julian/Development/venvs/venv/site-packages/click/decorators.py", line 71, in _make_command
    raise TypeError('Attempted to convert a callback into a '
TypeError: Attempted to convert a callback into a command twice.
```

when passed the other `Group` instance. The docstring looks at very least suspicious, so even if this isn't actually what I should be using to do this, something seems a bit off:

```
A shortcut decorator for declaring and attaching a group to the group. This takes the same arguments as group() but immediately registers the created command with this instance by calling into add_command().
```

where that reference to `group` seems to be to the method itself, so seems like possibly there was some copy pasting there that went awry.

**Comment by davidism** [comment]
Groups are commands. `cli.add_command(other_group)`
