### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'value'

### ISSUE THREAD

**Issue by sumanthratna** [pallets/click#1426]
```python3
import click


class ChoiceType(click.Choice):
    def __init__(self, typemap):
        super(ChoiceType, self).__init__(typemap.keys())
        self.typemap = typemap

    def convert(self, value, param, ctx):
        value = super(ChoiceType, self).convert(value, param, ctx)
        return self.typemap[value]


@click.command()
@click.option('-i', '--input-file', required=True, type=click.Path(exists=True, dir_okay=False))
@click.option('-r', '--update-rule', default='hebbian', type=click.Choice(['hebbian', 'anti_hebbian', 'random_walk'], case_sensitive=False))
@click.option('-o', '--output-file', default=click.Path('out.enc'), type=click.Path(dir_okay=False, writable=True))
@click.option('-K', default=8, type=int)
@click.option('-N', default=12, type=int)
@click.option('-L', default=4, type=int)
@click.option('-k', '--key-length', default='128', type=ChoiceType({str(x): x for x in [128, 192, 256]}))
@click.option('-v', '--iv-length', default='128', type=ChoiceType({str(x): x for x in range(0, 256 + 1, 4)}))
def main(input_file, update_rule, output_file, K, N, L, key_length, iv_length):
    print(input_file)
    print(update_rule)
    print(output_file)
    print(K)
    print(N)
    print(L)
    print(key_length)
    print(iv_length)
    # run some real computations


if __name__ == "__main__":
    main()
```

With the code above using `python run.py -i hello.txt`, I'm getting the following error:
```
Traceback (most recent call last):
  File "run.py", line 171, in <module>
    main()
  File ".../lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File ".../lib/python3.6/site-packages/click/core.py", line 716, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File ".../lib/python3.6/site-packages/click/core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File ".../lib/python3.6/site-packages/click/core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File ".../lib/python3.6/site-packages/click/core.py", line 1469, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File ".../lib/python3.6/site-packages/click/core.py", line 1790, in full_process_value
    return Parameter.full_process_value(self, ctx, value)
  File ".../lib/python3.6/site-packages/click/core.py", line 1441, in full_process_value
    value = self.get_default(ctx)
  File ".../lib/python3.6/site-packages/click/core.py", line 1745, in get_default
    return Parameter.get_default(self, ctx)
  File ".../lib/python3.6/site-packages/click/core.py", line 1382, in get_default
    rv = self.default()
TypeError: __call__() missing 1 required positional argument: 'value'
```

I'm using `pipenv` with `click` version 7.0.

**Comment by greyli** [comment]
Why are you set `default` to `click.Path('out.enc')`? It makes no sense.

```
@click.option('-o', '--output-file', default=click.Path('out.enc'), type=click.Path(dir_okay=False, writable=True))
```
Maybe what you want is set `default` to `'out.enc'`?

**Comment by sumanthratna** [comment]
Sorry, thanks for the help. I didn't realize that the mistake was caused by my code; I thought that the error was because of a mistake in Click's code.
