### ISSUE TITLE
File argument mode r+t can't be atomic

### ISSUE THREAD

**Issue by mvolfik** [pallets/click#1485]
### Expected Behavior

You should be able to write file atomically with mode "r+t" (allow both reading and writing)

```python
import click

@click.command()
@click.argument("file", type=click.File(mode="r+t", atomic=True))
def bug(file):
    pass

if __name__ == "__main__":
    bug()
```

### Actual Behavior

```pytb
Traceback (most recent call last):
  File "/tmp/bug.py", line 9, in <module>
    bug()
  File "/home/volfmatej/.local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/volfmatej/.local/lib/python3.8/site-packages/click/core.py", line 716, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/volfmatej/.local/lib/python3.8/site-packages/click/core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "/home/volfmatej/.local/lib/python3.8/site-packages/click/core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/volfmatej/.local/lib/python3.8/site-packages/click/core.py", line 1469, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/home/volfmatej/.local/lib/python3.8/site-packages/click/core.py", line 1438, in full_process_value
    value = self.process_value(ctx, value)
  File "/home/volfmatej/.local/lib/python3.8/site-packages/click/core.py", line 1428, in process_value
    return self.type_cast_value(ctx, value)
  File "/home/volfmatej/.local/lib/python3.8/site-packages/click/core.py", line 1417, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/home/volfmatej/.local/lib/python3.8/site-packages/click/core.py", line 1415, in _convert
    return self.type(value, self, ctx)
  File "/home/volfmatej/.local/lib/python3.8/site-packages/click/types.py", line 39, in __call__
    return self.convert(value, param, ctx)
  File "/home/volfmatej/.local/lib/python3.8/site-packages/click/types.py", line 437, in convert
    f, should_close = open_stream(value, self.mode,
  File "/home/volfmatej/.local/lib/python3.8/site-packages/click/_compat.py", line 501, in open_stream
    raise ValueError('Atomic writes only make sense with `w`-mode.')
ValueError: Atomic writes only make sense with `w`-mode.
```

### Environment

* Python version: 3.8.0
* Click version: 7.0

**Comment by davidism** [comment]
Use `w+t`

**Comment by mvolfik** [comment]
But w+t truncates the file first...

**Comment by fdavis** [comment]
```
>>> with open('myfile', mode='r') as f:
...  f.read()
... 
'oldcontent'
>>> with open('myfile', mode='r+t') as f:
...  f.write('newcontent')
... 
10
>>> with open('myfile', mode='r') as f:
...  f.read()
... 
'newcontent'
```

**Comment by mvolfik** [comment]
No, r+t doesn't append, but it allows both reading of the original file and writing data. So:
```python
with open("myfile", "w+t") as f:
    print(f.read())
    f.seek(1)
    f.write("gre")
    f.seek(0)
    print(f.read())
```
Output:
```
oldcontent
ogreontent
```

**Comment by davidism** [comment]
`atomic=True` has an explicit error when using "a+", I don't think it's intended to work with appending to files.

**Comment by mitsuhiko** [comment]
Effectively this is working as intended. See also https://github.com/pallets/click/issues/357
