### ISSUE TITLE
TypeError: fileno() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by Chr1st-oo** [pallets/click#1539]
### Expected Behavior

My CLI should work correctly when installed outside its development venv. These are some of the commands that produces the error.

```bash
mycli
```

```bash
mycli commandthatusesecho
```

```bash
mycli --help
```

### Actual Behavior

Instead it produces this kind of error when the CLI is being called in the terminal. It works well on commands that doesn't use ```click.echo()```.

#### My Project Structure

```
my_package\
	__init__.py
	cli.py
	my_module.py
	my_other_module.py
setup.py
```

### cli.py

```python
import click
from click import echo, types

@click.group()
def cli():
    """My CLI"""
    pass

@cli.command()
def commandthatusesecho():
    echo("Bad")
    
@cli.command()
def workingcommand():
    print("Good")
```

#### setup.py

```python
import setuptools

setuptools.setup(
	name="my_package",
    version="version",
    packages=setuptools.find_packages(),
    include_package_data=True,
    install_requires=[
        "click",
        "other_dependency"
    ],
    entry_points="""
    	[console_scripts]
    	mycli=my_package.cli:cli
    """
)
```

#### The Error

```pytb
Traceback (most recent call last):
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python38\Scripts\pydeezer-script.py", line 11, in <module>
    load_entry_point('py-deezer', 'console_scripts', 'pydeezer')()
  File "c:\users\desktop\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\desktop\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "c:\users\desktop\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 700, in make_cont
ext
    self.parse_args(ctx, args)
  File "c:\users\desktop\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1209, in parse_ar
gs
    echo(ctx.get_help(), color=ctx.color)
  File "c:\users\desktop\appdata\local\programs\python\python38\lib\site-packages\click\utils.py", line 230, in echo
    file = _default_text_stdout()
  File "c:\users\desktop\appdata\local\programs\python\python38\lib\site-packages\click\_compat.py", line 764, in func
    rv = wrapper_func()
  File "c:\users\desktop\appdata\local\programs\python\python38\lib\site-packages\click\_compat.py", line 459, in get_te
xt_stdout
    rv = _get_windows_console_stream(sys.stdout, encoding, errors)
  File "c:\users\desktop\appdata\local\programs\python\python38\lib\site-packages\click\_winconsole.py", line 356, in _g
et_windows_console_stream
    and _is_console(f)
  File "c:\users\desktop\appdata\local\programs\python\python38\lib\site-packages\click\_winconsole.py", line 343, in _i
s_console
    fileno = f.fileno()
TypeError: fileno() takes 0 positional arguments but 1 was given
```

### Environment

* Python version: Python 3.8.2
* Click version: 7.1.1

**Comment by Chr1st-oo** [comment]
Turns out the issue is my environment. I have a friend install and try it for me and it works for him.
