### ISSUE TITLE
Python 2.7 UnicodeEncodeError for Path Type in click 7.1.x (regression)

### ISSUE THREAD

**Issue by jorisroovers** [pallets/click#1670]
Hi, thanks for creating Click. Happy user for many years (and donated in the past)!

I believe I've found a bug wrt Unicode handling in the `Path` Option Type in python 2.7 in click 7.1.x. 

Click 7.0 doesn't exhibit this issue, so I believe it's a regression.

### Expected Behavior

Consider this code:

```python
from __future__ import print_function
import click

@click.command()
@click.option('--path', type=click.Path(exists=True))
def cli(path):
    print("path=", path)

if __name__ == "__main__":
    cli()
```
When invoking this code and passing a path name containing unicode in click 7.0, everything works as expected (in both python 3.x and 2.7).

```sh
# Python 2.7, click 7.0
(.venv27) /tmp $ pip freeze | grep -i click
Click==7.0
(.venv27)  /tmp $ python cli.py --path föo
Usage: cli.py [OPTIONS]
Try "cli.py --help" for help.

Error: Invalid value for "--path": Path "föo" does not exist.

# Python 3.8, click 7.0
(.venv38)  /tmp $ pip freeze | grep -i click
Click==7.0
(.venv38)  /tmp $ python cli.py --path föo
Usage: cli.py [OPTIONS]
Try "cli.py --help" for help.

Error: Invalid value for "--path": Path "föo" does not exist.
```

### Actual Behavior

When running the above code in python 2.7 on click 7.1.2, a `UnicodeEncodeError` occurs
```sh
(.venv27)  /tmp $ pip freeze | grep -i click
click==7.1.2
(.venv27)  /tmp $ python cli.py --path föo
# Traceback in block below occurs
```

```pytb
Traceback (most recent call last):
  File "cli.py", line 10, in <module>
    cli()
  File "/private/tmp/.venv27/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/private/tmp/.venv27/lib/python2.7/site-packages/click/core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/private/tmp/.venv27/lib/python2.7/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/private/tmp/.venv27/lib/python2.7/site-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/private/tmp/.venv27/lib/python2.7/site-packages/click/core.py", line 1623, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/private/tmp/.venv27/lib/python2.7/site-packages/click/core.py", line 1965, in full_process_value
    return Parameter.full_process_value(self, ctx, value)
  File "/private/tmp/.venv27/lib/python2.7/site-packages/click/core.py", line 1589, in full_process_value
    value = self.process_value(ctx, value)
  File "/private/tmp/.venv27/lib/python2.7/site-packages/click/core.py", line 1579, in process_value
    return self.type_cast_value(ctx, value)
  File "/private/tmp/.venv27/lib/python2.7/site-packages/click/core.py", line 1568, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/private/tmp/.venv27/lib/python2.7/site-packages/click/core.py", line 1565, in _convert
    return self.type(value, self, ctx)
  File "/private/tmp/.venv27/lib/python2.7/site-packages/click/types.py", line 46, in __call__
    return self.convert(value, param, ctx)
  File "/private/tmp/.venv27/lib/python2.7/site-packages/click/types.py", line 614, in convert
    self.path_type, filename_to_ui(value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 1: ordinal not in range(128)
```

It works as expected in python 3.x:

```sh
# Python 3.8, click 7.1.2
(.venv38) /tmp $ pip freeze | grep click
click==7.1.2
(.venv38) /tmp $ python cli.py --path föo
Usage: cli.py [OPTIONS]
Try 'cli.py --help' for help.

Error: Invalid value for '--path': Path 'föo' does not exist.
```

### Environment

* Python version: 2.7.13
* Click version: 7.1.2

**Comment by davidism** [comment]
Although the current release supports Python 2.7, I am no longer providing support for 2.7 myself. If you'd like to write a PR against that branch, I can review it and possibly make a release.
