### ISSUE TITLE
long option name not chosen with "/" prefix

### ISSUE THREAD

**Issue by davidism** [pallets/click#1673]
### Expected Behavior

The same option name should be chosen regardless of the prefix used.

```python
import click

@click.command()
@click.option("/t", "/test")
def cli(test):
    click.echo(test)
```

### Actual Behavior

 With `"-t", "--test"`, the option name is `test`. With the code above, the option name should also be `test`, but it is `t`.

```pytb
Traceback (most recent call last):
  File "example.py", line 21, in <module>
    cli()
  File "/home/david/Projects/click/src/click/core.py", line 1016, in __call__
    return self.main(*args, **kwargs)
  File "/home/david/Projects/click/src/click/core.py", line 969, in main
    rv = self.invoke(ctx)
  File "/home/david/Projects/click/src/click/core.py", line 1501, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/david/Projects/click/src/click/core.py", line 1270, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/david/Projects/click/src/click/core.py", line 707, in invoke
    return callback(*args, **kwargs)
TypeError: cli() got an unexpected keyword argument 't'
```

### Environment

* Python version: 3.8.5
* Click version: dev

**Comment by davidism** [comment]
[The docs](https://click.palletsprojects.com/en/7.x/options/#other-prefix-characters) mention that Windows-style prefixes are discouraged, and don't actually say how they're interpreted internally. The same thing would happen if `"-t", "-test"` (which is valid) was given. Click's rule is to choose the first long option, but "long" options are distinguished by a double prefix, not by how many characters there are in the name. In fact, `"/t", "//test"` does choose `test`.
