### ISSUE TITLE
NoneType parent context when calling directly into subcommand

### ISSUE THREAD

**Issue by Evidlo** [pallets/click#1758]
I want to create a second entry point `legoman_cgi` in my setup.py like so:

``` python
setup(
    entry_points={
        'console_scripts': [
            'legoman = legoman.legoman:main',
            'legoman_cgi = legoman.legoman:cgi'
        ],
    },
)
```

The subcommand `cgi` and its parent group look like this:

``` python
@click.group()
@click.option('--template_dir', envvar='TEMPLATE_DIR', default='templates', metavar='PATH')
@click.pass_context
def main(ctx, debug, content_dir, output_dir, template_dir):
    ...
    ctx.j2env = Environment(loader=FileSystemLoader([template_dir]))

@main.command(short_help="read file from stdin", help="read file from stdin")
@click.argument("filetype", envvar='FILETYPE', type=click.Choice(['md', 'j2']))
@click.pass_context
def cgi(ctx, filetype):
    ...
    if filetype == 'md':
        print(render_md(text, ctx.parent.j2env))
```

However, when I try to call `legoman_build`, I get an error because `ctx.parent` is None.

```
[evan@blackbox legoman] FILETYPE=md TEMPLATE_DIR=/home/evan/resources/evanw.org/templates/ legoman_cgi <<< '# hello'
Traceback (most recent call last):
  File "/home/evan/resources/venv3/bin/legoman_cgi", line 11, in <module>
    load_entry_point('legoman', 'console_scripts', 'legoman_cgi')()
  File "/home/evan/resources/venv3/lib/python3.9/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/evan/resources/venv3/lib/python3.9/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/evan/resources/venv3/lib/python3.9/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/evan/resources/venv3/lib/python3.9/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/evan/resources/venv3/lib/python3.9/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/evan/resources/legoman/legoman/legoman.py", line 130, in cgi
    print(render_md(text, ctx.parent.j2env))
AttributeError: 'NoneType' object has no attribute 'j2env'
```

Am I doing something wrong here or is this use case not supported?

[Full code](https://github.com/Evidlo/legoman/blob/62d9e7f942aa4950313ccd6d070ae59cb38f9046/legoman/legoman.py)

**Comment by Evidlo** [comment]
I have a relatively simple workaround [here](https://github.com/Evidlo/legoman/commit/81eb59fcaf75231ca56a1779c18233d5b7d91701), but if there's a built in way to do this, please let me know.

**Comment by davidism** [comment]
https://click.palletsprojects.com/en/7.x/commands/#nested-handling-and-contexts
