### ISSUE TITLE
TypeError raised when command takes capitalized argument

### ISSUE THREAD

**Issue by GodSaveTheDoge** [pallets/click#1947]
### Description:
When you add a command that expects a capitalized argument a TypeError is raised (`TypeError: hello() got an unexpected keyword argument 'name'`).

### How to replicate:
- paste this in a file:
```python
import click

@click.command()
@click.argument("nAme")
def hello(nAme):
    click.echo(f'Hello {nAme}!')

if __name__ == "__main__":
    hello()
```
- run it
```
$ python github_example.py GodSaveTheDoge
Traceback (most recent call last):
  File "github_example.py", line 9, in <module>
    hello()
  File "/home/doggo/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/doggo/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/doggo/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/doggo/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
TypeError: hello() got an unexpected keyword argument 'name'
```

### Expected behavior:
I expected it to output `Hello GodSaveTheDoge!`

Environment:

- Python version: `3.8.5`
- Click version: `7.1.2`

**Comment by davidism** [comment]
Click does some normalization on the command and argument names. I don't think we need to change this.

**Comment by GodSaveTheDoge** [comment]
you could at least hint that in the documentation...
