### ISSUE TITLE
json.decoder.JSONDecodeError when running click.testing.CliRunner

### ISSUE THREAD

**Issue by stmlange** [pallets/click#1984]
Hello,
thank you for this project. I'm currently having an issue while running the `CliRunner` from `click.testing`.
I'm not sure by what this is caused and I also don't know how to trace it down:

```
Traceback (most recent call last):
  File "/python3.8/site-packages/click/testing.py", line 408, in invoke
    return_value = cli.main(args=args or (), prog_name=prog_name, **extra)
  File "/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 19 (char 18)
```
I would greatly appreciate any troubleshooting hints.

Environment:
- Python version: Python 3.8.1
- Click version: 8.0.1

**Comment by stmlange** [comment]
I think I finally found it
cat skeleton.py
```python
import click
import json


@click.command()
@click.argument('content')
def hello(content):
    print(json.loads(content))


if __name__ == '__main__':
    hello()

```

and
cat test_skeleton.py
```python
import pytest
import logging
import traceback

from click_issue_1984.skeleton import hello
from click.testing import CliRunner


def test_foo():
    # CLI Runner
    cli_runner = CliRunner()
    command_args = [
        "content"
    ]

    result = cli_runner.invoke(hello, command_args)

    print(f"{result.stdout=}")
    print(f"{result.stderr_bytes=}")
    print(f"{result.exit_code=}")
    print(f"{result.exc_info=}")
    print(f"{result.exception=}")
    raise ValueError("broken") from result.exception

```

yields a
```
--------------------------------------------------------- Captured stdout call ---------------------------------------------------------
result.stdout=''
result.stderr_bytes=None
result.exit_code=1
result.exc_info=(<class 'json.decoder.JSONDecodeError'>, JSONDecodeError('Expecting value: line 1 column 1 (char 0)'), <traceback object at 0x000001C38C40D9C0>)
result.exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
```
One really needs to print / consume the `result.exc_info`to get the underlying error in the application e.g. via:
```
logging.error("Exit code was not null!", exc_info=result.exc_info)
```
or
```
def __get_traceback(exc_info):
    if isinstance(exc_info, BaseException):
        exc_info = (type(exc_info), exc_info, exc_info.__traceback__)
    elif not isinstance(exc_info, tuple):
        exc_info = sys.exc_info()

    return "\n".join(traceback.format_exception(exc_info[0], exc_info[1], exc_info[2]))

# ....
print(f"Exception Trace: '{__get_traceback(result.exc_info)}'")
```
