### ISSUE TITLE
On windows, all arguments are expanded, leading to issues with square brackets in argument values

### ISSUE THREAD

**Issue by sonologic** [pallets/click#2049]
On windows, Click will expand arguments (interpolating environment variables, globbing filenames). This was added as a feature because windows CMD doesn't do any of this itself, as opposed to unix shells.

Example program:
```
import click

@click.command()
@click.argument('test')
def main(test):
    print(test)

if __name__ == '__main__':
    main()
```

Running this with a particular xpath query gives:

```
C:\>Test\clicktest.py ".//storage/*[@attribute='zcl:commissioning:install-code']/text()"
Traceback (most recent call last):                                                  
  File "C:\Test\clicktest.py", line 9, in <module>       
    main()                                                                      
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)          
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\click\core.py", line 1049, in main
args = _expand_args(args)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\click\utils.py", line 572, in _expand_args
    matches = glob(arg, recursive=glob_recursive)
  File "C:\Program Files (x86)\Python39-32\lib\glob.py", line 22, in glob
    return list(iglob(pathname, recursive=recursive))
  File "C:\Program Files (x86)\Python39-32\lib\glob.py", line 74, in _iglob
    for dirname in dirs:
  File "C:\Program Files (x86)\Python39-32\lib\glob.py", line 75, in _iglob
    for name in glob_in_dir(dirname, basename, dironly):
  File "C:\Program Files (x86)\Python39-32\lib\glob.py", line 86, in _glob1
    return fnmatch.filter(names, pattern)
  File "C:\Program Files (x86)\Python39-32\lib\fnmatch.py", line 58, in filter
    match = _compile_pattern(pat)
  File "C:\Program Files (x86)\Python39-32\lib\fnmatch.py", line 52, in _compile_pattern
    return re.compile(res).match
  File "C:\Program Files (x86)\Python39-32\lib\re.py", line 252, in compile
    return _compile(pattern, flags)
  File "C:\Program Files (x86)\Python39-32\lib\re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Program Files (x86)\Python39-32\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Program Files (x86)\Python39-32\lib\sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Program Files (x86)\Python39-32\lib\sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Program Files (x86)\Python39-32\lib\sre_parse.py", line 834, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\Program Files (x86)\Python39-32\lib\sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Program Files (x86)\Python39-32\lib\sre_parse.py", line 598, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
re.error: bad character range l-c at position 43 
C:\>
```

I expected:
```
C:\>Test\clicktest.py ".//storage/*[@attribute='zcl:commissioning:install-code']/text()"
.//storage/*[@attribute='zcl:commissioning:install-code']/text()
C:\>
```

In my particular use-case, adding `windows_expand_args=False` to the invocation of `main` is acceptable, but that disables expansion for all argument, which is rather binary and may not be enough for others.

Since I have a work-around, don't spend time on this on my account. Just thought I'd mention this. Ideally, this would be something that could be set per-argument, but of course this expansion happens before actually parsing the arguments. At that point it isn't yet known which argument is going to be parsed as which `click.option` or `click.argument`.

Environment:

- Python version: 3.9.6 (32 bit)
- Click version: 8.0.1

**Comment by davidism** [comment]
If your want other behavior, you'll need to disable Click's as you've already shown then write your own.
