### ISSUE TITLE
TypeError: can only concatenate tuple (not "list") to tuple

### ISSUE THREAD

**Issue by cnicodeme** [pallets/click#2104]
When running Click v7.1.2 on Python 3.10.0, there is a TypeError exception on click/core.py, line 914:

> TypeError: can only concatenate tuple (not "list") to tuple

Here's the stack:

```
Traceback (most recent call last):
  File "/var/www/project/manage.py", line 13, in <module>
    manager.run()
  File "/var/www/project/surge/manager/manager.py", line 60, in run
    return self.cli()
  File "/var/www/project/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/var/www/project/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/var/www/project/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/www/project/env/lib/python3.10/site-packages/click/core.py", line 1257, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/var/www/project/env/lib/python3.10/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/var/www/project/env/lib/python3.10/site-packages/click/core.py", line 1044, in parse_args
    parser = self.make_parser(ctx)
  File "/var/www/project/env/lib/python3.10/site-packages/click/core.py", line 965, in make_parser
    for param in self.get_params(ctx):
  File "/var/www/project/env/lib/python3.10/site-packages/click/core.py", line 914, in get_params
    rv = rv + [help_option]
```

**Comment by cnicodeme** [comment]
Sorry for my late reply here, but I agree that I've created a Command directly so it's definitely an issue on my end ;)
Sorry for the troubles!
