### ISSUE TITLE
bug or nothing?

### ISSUE THREAD

**Issue by 1170301013** [pallets/click#2118]
Hello, I'm from China. I don't know what happened when I use Click to run a demo on Windows. If I use version 7.1+ , I get this feedback:
```
Traceback (most recent call last):
  File "click_test.py", line 36, in <module>
    pr()
  File "C:\Python27\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python27\lib\site-packages\click\core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "C:\Python27\lib\site-packages\click\core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "C:\Python27\lib\site-packages\click\core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "C:\Python27\lib\site-packages\click\core.py", line 1623, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "C:\Python27\lib\site-packages\click\core.py", line 1964, in full_process_value
    return self.prompt_for_value(ctx)
  File "C:\Python27\lib\site-packages\click\core.py", line 1940, in prompt_for_value
    value_proc=lambda x: self.process_value(ctx, x),
  File "C:\Python27\lib\site-packages\click\termui.py", line 147, in prompt
    value = prompt_func(prompt)
  File "C:\Python27\lib\site-packages\click\termui.py", line 128, in prompt_func
    echo(text, nl=False, err=err)
  File "C:\Python27\lib\site-packages\click\utils.py", line 272, in echo
    file.write(message)
  File "C:\Python27\lib\site-packages\click\_winconsole.py", line 213, in write
    return self.buffer.write(x)
IOError: [Errno 0] Error
```
But when I use version under 7.1 like 7.0 , it's ok, what happened between this two version? It seems be ok when I replace Chinese with English or still use Chinese but run on Linux.
Here is my demo:
```
import click
import sys
reload(sys)
sys.setdefaultencoding('utf-8')


@click.command()
@click.option('--name', type=str, default=u'你好', help=u'input name', prompt=u"请输入姓名", show_default=True)
@click.option('--age', type=int, help=u'input age', prompt=u"请输入年龄", hide_input=True, confirmation_prompt=True)
def pr(name,  # type: str
       age  # type: int
       ):
    """

    Args:
        name:input name
        age:input age

    Returns: nothing

    """
    click.echo(name)


if __name__ == '__main__':
    pr()
```
Because 7.1.2 is the last version of python2, so it will be use for a long time?

**Comment by davidism** [comment]
Sorry, I can't help you with this. Python 2 and Click 7.1.x are no longer supported. Upgrade to the latest Python 3 and Click 8.0.x.
