### ISSUE TITLE
CliRunner.Result has stdout and stderr mixed

### ISSUE THREAD

**Issue by gitpushdashf** [pallets/click#2136]
Related:  #1761

CliRunner.Result seems to have stdout and stderr mixed.

Test code, ran on 8.0.3:

```
import click
from click.testing import CliRunner

runner = CliRunner()


@click.command("hello")
def hello() -> None:
    click.echo("Hello!")
    click.echo("World!", err=True)


def test_hello() -> None:
    result = runner.invoke(hello, [])
    assert result.stdout == "Hello!\n"
    assert result.output == "Hello!\n"
    assert result.stderr == "World!\n"


if __name__ == "__main__":
    click.echo("Running tests...")
    test_hello()
    click.echo("Success!")
```

```
$ python3 clickitorticket.py
Running tests...
Traceback (most recent call last):
  File "clickitorticket.py", line 22, in <module>
    test_hello()
  File "clickitorticket.py", line 15, in test_hello
    assert result.stdout == "Hello!\n"
AssertionError
```

Setting `deprecated="some string"` also runs into this:

```
import click
from click.testing import CliRunner

runner = CliRunner()


@click.command("hello")
def hello() -> None:
    click.echo("Hello!")
    click.echo("World!", err=True)


@click.command("goodbye", deprecated="This is deprecated in favor of hello.")
def goodbye() -> None:
    click.echo("Bye!")


def test_hello() -> None:
    result = runner.invoke(hello, [])
    assert result.stdout == "Hello!\n"
    assert result.output == "Hello!\n"
    assert result.stderr == "World!\n"


def test_goodbye() -> None:
    result = runner.invoke(goodbye, [])
    assert "DeprecationWarning" not in result.stdout
    assert result.stdout == "Bye!\n"
    assert result.output == "Bye!\n"
    assert "DeprecationWarning" in result.stderr



if __name__ == "__main__":
    click.echo("Running tests...")
    test_goodbye()
    test_hello()
    click.echo("Success!")
```

```
$ python clickitorticket.py
Running tests...
Traceback (most recent call last):
  File "clickitorticket.py", line 36, in <module>
    test_goodbye()
  File "clickitorticket.py", line 27, in test_goodbye
    assert "DeprecationWarning" not in result.stdout
AssertionError
```

**Comment by davidism** [comment]
Yes, that is the default behavior. See the `mix_stderror` parameter: https://click.palletsprojects.com/en/8.0.x/api/#click.testing.CliRunner

**Comment by gitpushdashf** [comment]
Ah, great. Thank you so much!
