### ISSUE TITLE
Cannot import name "get_terminal_size" from "click.termui"

### ISSUE THREAD

**Issue by robert-taylor-maersk** [pallets/click#2229]
**Error:**

Attempting to install the typer python module (which uses click) give the following error since 8.1.0 was released.

```
ImportError: cannot import name 'get_terminal_size' from 'click.termui' (/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/click/termui.py)
```

**To reproduce:**

```
❯ pipenv install typer click==8.1.0

❯ python
Python 3.9.7 (default, Sep  9 2021, 23:20:13)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import typer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robert/.local/share/virtualenvs/EMP-Replicators-1sUNfoM1/lib/python3.9/site-packages/typer/__init__.py", line 12, in <module>
    from click.termui import get_terminal_size as get_terminal_size
ImportError: cannot import name 'get_terminal_size' from 'click.termui' (/home/robert/.local/share/virtualenvs/EMP-Replicators-1sUNfoM1/lib/python3.9/site-packages/click/termui.py)
>>>
```

**Workaround**
```
❯ pipenv install typer click==8.0.4

❯ python
Python 3.9.7 (default, Sep  9 2021, 23:20:13)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import typer
>>>
```

**Comment by robert-taylor-maersk** [comment]
Apologies, I see from the release notes that `get_terminal_size` is deprecated.
I will raise an issue on `typer` instead.

> Remove previously deprecated code. [:pr:`2130`](https://github.com/pallets/click/blob/main/CHANGES.rst#id3)
`Group.resultcallback` is renamed to `result_callback`.
autocompletion parameter to Command is renamed to `shell_complete`.
`get_terminal_size` is removed, use `shutil.get_terminal_size` instead.
`get_os_args` is removed, use `sys.argv[1:]` instead.
