### ISSUE TITLE
confirm UnicodeDecodeError

### ISSUE THREAD

**Issue by sniiick** [pallets/click#2403]
`click.confirm()` sometimes may raise UnicodeDecodeError on `visible_prompt_func` call

Several terminals control input stdin in different ways. Most of them are linux compatible and work fine, but some not.
E.G. PyCharm default integrated terminal with default terminal settings (inherited from user .*rc) may cause UnicodeDecodeError on several inputs.

Exact way to reproduce:
1. Run click app with click.confirm() or click.prompt() calls in PyCharm integrated terminal
2. Start typing
3. Backspace some symbols
4. Press enter

Stacktrace:
```
Continue? [y/N]: N
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/app", line 8, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/app/app.py", line 45, in handle
    click.confirm(f'Continue?', abort=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/termui.py", line 235, in confirm
    value = visible_prompt_func(" ").lower().strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte
```

Expected behaviour:
UnicodeDecodeError is handled with user notification
Seems that `except (KeyboardInterrupt, EOFError)` is not enough for `click.confirm` func

Environment:

- Python version: 3.10
- Click version: 8.1.2
- OS: macOS Monterey 12.6
- PyCharm 2022.2 Pro
- Shell: zsh 5.8.1

**Comment by davidism** [comment]
This sounds like a bug that should be reported to PyCharm.
