### ISSUE TITLE
`TypeError: isinstance() arg 2 must be a type or tuple of types` when `click.Path(path_like=True)`

### ISSUE THREAD

**Issue by Anthonyive** [pallets/click#2498]
**python Trackback**
```python
Traceback (most recent call last):
  File "./scripts/abc.py", line 43, in <module>
    main()
  File "/pkg/qct/dragon/dragon_compiler/python/default/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/pkg/qct/dragon/dragon_compiler/python/default/lib/python3.8/site-packages/click/core.py", line 1052, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/pkg/qct/dragon/dragon_compiler/python/default/lib/python3.8/site-packages/click/core.py", line 914, in make_context
    self.parse_args(ctx, args)
  File "/pkg/qct/dragon/dragon_compiler/python/default/lib/python3.8/site-packages/click/core.py", line 1370, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/pkg/qct/dragon/dragon_compiler/python/default/lib/python3.8/site-packages/click/core.py", line 2347, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/pkg/qct/dragon/dragon_compiler/python/default/lib/python3.8/site-packages/click/core.py", line 2303, in process_value
    value = self.type_cast_value(ctx, value)
  File "/pkg/qct/dragon/dragon_compiler/python/default/lib/python3.8/site-packages/click/core.py", line 2291, in type_cast_value
    return convert(value)
  File "/pkg/qct/dragon/dragon_compiler/python/default/lib/python3.8/site-packages/click/types.py", line 75, in __call__
    return self.convert(value, param, ctx)
  File "/pkg/qct/dragon/dragon_compiler/python/default/lib/python3.8/site-packages/click/types.py", line 891, in convert
    return self.coerce_path_result(rv)
  File "/pkg/qct/dragon/dragon_compiler/python/default/lib/python3.8/site-packages/click/types.py", line 820, in coerce_path_result
    if self.type is not None and not isinstance(rv, self.type):
TypeError: isinstance() arg 2 must be a type or tuple of types
```

**How to reproduce**

```python
import click, os
@click.option(
    "--list",
    "list",
    type=click.Path(exists=True, file_okay=True, readable=True, path_type=True),
    required=False,
)
def main(list: os.PathLike):
    pass
```

```bash
python3 abc.py --list /tmp/some-folder/list
```
Removing `path_like=True` will solve the problem, but no pathlib integration anymore.

**Expected Bahavior**

I expected no trackback error on this because I want the path to be converted to pathlib with this option.

Environment:

- Python version: 3.8.1
- Click version: 8.0.3

**Comment by davidism** [comment]
`path_type=pathlib.Path`, not `True`.
