### ISSUE TITLE
Failure to use typing.NewType as the type for an option

### ISSUE THREAD

**Issue by mthorpe7** [pallets/click#2773]
[`typing.NewType`](https://mypy.readthedocs.io/en/stable/more_types.html#newtypes) is a cheap way to create an alias type for type checking only (at runtime it is the underlying type). I was hoping to use this one in a `@click.option` parameter/type list, but this does something unexpected (although I can understand why it behaves like this).

```python
from typing import NewType, reveal_type
import click

UserId = NewType("UserId", int)

@click.command
@click.option("--user-id", type=UserId, default=UserId(1))
def main(user_id: UserId):
    reveal_type(UserId)
    reveal_type(user_id)
    assert isinstance(user_id, int)

if __name__ == "__main__":
    main()
```

With the default, this is happy:

```console
$ python cli.py 
Runtime type is 'NewType'
Runtime type is 'int'
```

when passing a value, it isn't:

```console
$ python cli.py --user-id 10
Runtime type is 'NewType'
Runtime type is 'str'
Traceback (most recent call last):
  File "/work/cli.py", line 17, in <module>
    main()
  File "/work/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/work/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/cli.py", line 13, in main
    assert isinstance(user_id, int)
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

Environment:

- Python version: Python 3.12.5
- Click version: click-8.1.7

**Comment by davidism** [comment]
`type` is the Click type, not the Python type. You'd pass `int` there. If you know of a way to introspect that something is a `NewType` at runtime, and find out what it aliases (`int`) then that can be added to the automatic conversions. But in general, you're expecting a level of typing support that we just don't do.
