### ISSUE TITLE
Contexts with nested handling does not work with setup tools entry points

### ISSUE THREAD

**Issue by kghosesbg** [pallets/click#571]
Hi Folks,

I was bummed to find that nested commands and passing contexts does not work when using the setup tools entry points mechanism. (Minimal example below). I love click and use it a lot. Thanks for creating this package!

Best
-Kaushik

`yourscript.py`

```
import click

@click.group()
@click.option('--debug/--no-debug', default=False)
@click.pass_context
def cli(ctx, debug):
    ctx.obj['DEBUG'] = debug

@cli.command()
@click.pass_context
def sync(ctx):
    click.echo('Debug is %s' % (ctx.obj['DEBUG'] and 'on' or 'off'))

if __name__ == '__main__':
    cli(obj={})
```

`setup.py`

```
from setuptools import setup

setup(
    name='yourscript',
    version='0.1',
    py_modules=['yourscript'],
    install_requires=[
        'Click',
    ],
    entry_points='''
        [console_scripts]
        yourscript=yourscript:cli
    ''',
)
```

**Comment by untitaker** [comment]
It does, please show how you're invoking the script.

**Comment by kghosesbg** [comment]
Thanks for your quick reply! Here is my invocation:

```
kghose$ yourscript 
Usage: yourscript [OPTIONS] COMMAND [ARGS]...

Options:
  --debug / --no-debug
  --help                Show this message and exit.

Commands:
  sync
kghose$ yourscript --debug sync
Traceback (most recent call last):
  File "/Users/kghose/.venvs/click-bug/bin/yourscript", line 9, in <module>
    load_entry_point('yourscript==0.1', 'console_scripts', 'yourscript')()
  File "/Users/kghose/.venvs/click-bug/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kghose/.venvs/click-bug/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/kghose/.venvs/click-bug/lib/python2.7/site-packages/click/core.py", line 1057, in invoke
    Command.invoke(self, ctx)
  File "/Users/kghose/.venvs/click-bug/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kghose/.venvs/click-bug/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/kghose/.venvs/click-bug/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/kghose/Sandbox/click-bug/yourscript.py", line 7, in cli
    ctx.obj['DEBUG'] = debug
TypeError: 'NoneType' object does not support item assignment
```

**Comment by untitaker** [comment]
Ah, I see.

These lines is irrelevant with setuptools entry points (they are an alternative to the same behavior):

    if __name__ == '__main__':
        cli(obj={})

 `cli` is called without arguments when running `yourscript`, as configured in this block in `setup.py`:

    entry_points='''
        [console_scripts]
        yourscript=yourscript:cli
    ''',

What you can do is checking whether `ctx.obj` is None and replace it *within* the script.

**Comment by kghosesbg** [comment]
Ah, cool. I'm assuming it is sufficient to do this check in the `cli` function since everything is propagated from then on? Thanks very much for your reply. I would only request that a relevant note is added to the docs. Thanks!

**Comment by untitaker** [comment]
I guess it would go into http://click.pocoo.org/5/setuptools/#setuptools-integration. Care to do a PR?

**Comment by kghosesbg** [comment]
Done: https://github.com/pallets/click/pull/572
