### ISSUE TITLE
pass_context with multiple option

### ISSUE THREAD

**Issue by Kiyundai** [pallets/click#573]
Hi,
I'm trying to achieve a function with multiple tuple command : 
`putitem --item dog 123 --item cat 456`

Without click.pass_context this command work well, but i would like to use click.pass_context (for the own needs of my real application)
I have the following code : 
```python
#!/usr/bin/python
import click

@click.command()
@click.option('--item', multiple=True, type=(str, str))
@click.pass_context
def putitem(item):
    click.echo(item)

if __name__ == '__main__' :
    putitem()
``` 
but i got this error 
```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    putitem()
  File "[...]/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "[...]/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "[...]/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "[...]/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
TypeError: putitem() got multiple values for keyword argument 'item'
```

In my real application, the context is initialize, and work well with my other command (which don't use multi tuple), but i get the same error 
Any idea why i can fix this ? 

I use click 6.6 on python 2.7.3 Debian Wheezy

**Comment by Kiyundai** [comment]
Ok find the answer, i forget to insert ctx as a parameters in my function
Good answer : 
```python 
#!/usr/bin/python
import click 

@click.command()
@click.option('--item', multiple=True, type=(str, str))
@click.pass_context
def putitem(ctx, item):
    click.echo(item)

if __name__ == '__main__' :
    putitem()
```
