### ISSUE TITLE
UTF8 character support?

### ISSUE THREAD

**Issue by swaathi** [pallets/click#688]
I'm trying to create an CLI tool that analyzes some text. However this text contains UTF8 characters, such as emoticons, like 🎉. 

This is the function,

```
@main.command()
@click.option('--text', '-t', help='Sample text')
def clean(text):
    click.echo(text)
```

Whenever I pass in a text with an UTF8 symbol, this is what click throws,

```
➜  ~ unen clean -t "Our vision is to make products that are insanely great, that would help people work smarter and better. I truly believe in this vision, and I know that some day, this is going to take us somewhere.🍕"
Traceback (most recent call last):
  File "/usr/local/bin/unen", line 9, in <module>
    load_entry_point('UnderstandEngine==0.1.2', 'console_scripts', 'unen')()
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "build/bdist.macosx-10.11-x86_64/egg/understand_engine/cli/cli.py", line 45, in clean
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 197-198: ordinal not in range(128)
```

I've tried to clean it out, but I realized it's an issue within click itself. Would be great if someone can point me in the right direction with this.

**Comment by Lguyogiro** [comment]
It looks like this can be fixed by decoding the args as utf-8 in core.py 
line 679:
       `args = [arg.decode('utf-8') for arg in get_os_args()]`
and line 781:
        `args = [arg.decode('utf-8') for arg in args]`

I've created a pull request that adds an 'encoding' parameter to the main function and decodes accordingly.

**Comment by jcrotts** [comment]
Closing this because it is probably not going to be changed. See the discussion on https://github.com/pallets/click/issues/1212 . Thank you for the report.
