### ISSUE TITLE
click does not work in windows console

### ISSUE THREAD

**Issue by jrxpert** [pallets/click#744]
Hi, I tried using your library but when I tried running under windows I got the following error:

`Traceback (most recent call last):`
`  File "test.py", line 12, in <module>`
`    click.echo('Continue? [yn] ', nl=False)`
`  File "xxx\Lib\site-packages\click\utils.py", line 217, in echo`
`    file = _default_text_stdout()`
`  File "xxx\Lib\site-packages\click\_compat.py", line 621, in func`
`    rv = wrapper_func()`
`  File "xxx\Lib\site-packages\click\_compat.py", line 385, in get_text_stdout`
`    rv = _get_windows_console_stream(sys.stdout, encoding, errors)`
`  File "xxx\Lib\site-packages\click\_winconsole.py", line 264, in _get_windows_console_stream`
`    f = getattr(f, 'buffer')`
`AttributeError: 'TextTranscodingWrapper' object has no attribute 'buffer'`

**Comment by untitaker** [comment]
Done, thanks!

**Comment by 2press** [comment]
Similar error here @untitaker
```
Traceback (most recent call last):
  File "D:\Code\GitHub\StarCraft-Casting-Tool\scctool\tasks\webapp.py", line 189, in run
    self.application.run(port=65010)
  File "c:\users\tasch\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 938, in run
    cli.show_server_banner(self.env, self.debug, self.name, False)
  File "c:\users\tasch\appdata\local\programs\python\python36-32\lib\site-packages\flask\cli.py", line 629, in show_server_banner
    click.echo(message)
  File "c:\users\tasch\appdata\local\programs\python\python36-32\lib\site-packages\click\utils.py", line 217, in echo
    file = _default_text_stdout()
  File "c:\users\tasch\appdata\local\programs\python\python36-32\lib\site-packages\click\_compat.py", line 621, in func
    rv = wrapper_func()
  File "c:\users\tasch\appdata\local\programs\python\python36-32\lib\site-packages\click\_compat.py", line 385, in get_text_stdout
    rv = _get_windows_console_stream(sys.stdout, encoding, errors)
  File "c:\users\tasch\appdata\local\programs\python\python36-32\lib\site-packages\click\_winconsole.py", line 264, in _get_windows_console_stream
    f = getattr(f, 'buffer')
AttributeError: 'FileWrapper' object has no attribute 'buffer'
```

**Comment by 2press** [comment]
Fixed this by updating to the current master branch, but now I encounter this error:
```
  File "site-packages\click\_compat.py", line 105, in __getattr__
AttributeError: 'NullWriter' object has no attribute 'closed'
```
