### ISSUE TITLE
Test fails with python 3.6

### ISSUE THREAD

**Issue by luigino** [pallets/click#748]
I know python3 is not particularly recommended for Click, but this doesn't seem to be text-related:

```
+ /usr/bin/python3 setup.py test
running test
running egg_info
writing click.egg-info/PKG-INFO
writing dependency_links to click.egg-info/dependency_links.txt
writing top-level names to click.egg-info/top_level.txt
reading manifest file 'click.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
warning: no previously-included files matching '*.pyc' found under directory 'tests'
warning: no previously-included files matching '*.pyo' found under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'examples'
warning: no previously-included files matching '*.pyo' found under directory 'examples'
no previously-included directories found matching 'docs/_build'
writing manifest file 'click.egg-info/SOURCES.txt'
running build_ext
_winconsole (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: _winconsole (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: _winconsole
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/abuild/rpmbuild/BUILD/click-6.7/click/_winconsole.py", line 17, in <module>
    import msvcrt
ModuleNotFoundError: No module named 'msvcrt'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Bad exit status from /var/tmp/rpm-tmp.MgXmdL (%check)
```

**Comment by ThiefMaster** [comment]
It looks like you are trying to run the tests using python's unittest module - but click uses pytest for tests. Use `make test` to run the tests.

**Comment by untitaker** [comment]
As @ThiefMaster said you are running the tests incorrectly.
