### ISSUE TITLE
`TypeError` is raised because of 'Attempted to convert a callback into a command twice'

### ISSUE THREAD

**Issue by pranair** [pallets/click#779]
The following code 

```python
@click.command(metavar='[OPTIONS] name')
@click.group()
@click.option('--source', type=click.STRING)  
@click.option('--range', type=click.STRING)
@click.option('--path', type=click.STRING)  
@click.option('--bundle', type=click.STRING)
@click.option('--name', type=click.STRING)
def download(source, download_range, path, bundle, name):
	pass
```
produces the traceback

```
Traceback (most recent call last):
  File "/home/usrr/Code/Code/cli.py", line 17, in <module>
    @click.option('--name', type=click.STRING, help='Name of the manga')
  File "/home/usrr/.pyenv/versions/venv/lib/python2.7/site-packages/click/decorators.py", line 115, in decorator
    cmd = _make_command(f, name, attrs, cls)
  File "/home/usrr/.pyenv/versions/venv/lib/python2.7/site-packages/click/decorators.py", line 71, in _make_command
    raise TypeError('Attempted to convert a callback into a '
TypeError: Attempted to convert a callback into a command twice.
```
The problem does not seem to be caused by the '@click.command` not the `--name` argument. Commenting out the `@click.command` seems to solve the problem.

**Comment by pranair** [comment]
It seems that `click.group` and `click.command` don't go together. `click.group` creates a new instance of the class `Group` which is a subclass of `Command` thus the error.
