### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by PureWhiteWu** [pallets/click#882]
```
$ cli
Traceback (most recent call last):
  File "cli", line 11, in <module>
    sys.exit(root())
  File "venv/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "venv/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "venv/local/lib/python2.7/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "venv/local/lib/python2.7/site-packages/click/core.py", line 1018, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "venv/local/lib/python2.7/site-packages/click/core.py", line 876, in parse_args
    opts, args, param_order = parser.parse_args(args=args)
  File "venv/local/lib/python2.7/site-packages/click/parser.py", line 267, in parse_args
    self._process_args_for_options(state)
  File "venv/local/lib/python2.7/site-packages/click/parser.py", line 293, in _process_args_for_options
    self._process_opts(arg, state)
  File "venv/local/lib/python2.7/site-packages/click/parser.py", line 414, in _process_opts
    self._match_long_opt(norm_long_opt, explicit_value, state)
  File "venv/local/lib/python2.7/site-packages/click/parser.py", line 324, in _match_long_opt
    raise NoSuchOption(opt, possibilities=possibilities)
  File "venv/local/lib/python2.7/site-packages/click/exceptions.py", line 146, in __init__
    UsageError.__init__(self, message, ctx)
  File "venv/local/lib/python2.7/site-packages/click/exceptions.py", line 38, in __init__
    ClickException.__init__(self, message)
  File "venv/local/lib/python2.7/site-packages/click/exceptions.py", line 14, in __init__
    message = message.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 17: ordinal not in range(128)
```
os: ubuntu server 16.04 x86_64

**Comment by mitsuhiko** [comment]
Cannot reproduce this without seeing the source of the cli command.

**Comment by BeyondEvil** [comment]
Ran in to this today as well @mitsuhiko What do you need from me to reproduce?

```dpo-cli deploy \
>     dpo-controller-frontend \
>     --env stage \
>     --assets-version develop-114b73d9
### dpo-cli > 0.8.5... up-to-date
     ---------------------
Traceback (most recent call last):
  File "/usr/local/bin/../lib/node_modules/@dporganizer/dpo-cli/scripts/deploy/python-helper/deploy.py", line 394, in <module>
    deploy(obj={})
  File "/Users/dev/Library/Python/2.7/lib/python/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dev/Library/Python/2.7/lib/python/site-packages/click/core.py", line 696, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/Users/dev/Library/Python/2.7/lib/python/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/Users/dev/Library/Python/2.7/lib/python/site-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/Users/dev/Library/Python/2.7/lib/python/site-packages/click/core.py", line 1396, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/Users/dev/Library/Python/2.7/lib/python/site-packages/click/core.py", line 1365, in full_process_value
    value = self.process_value(ctx, value)
  File "/Users/dev/Library/Python/2.7/lib/python/site-packages/click/core.py", line 1355, in process_value
    return self.type_cast_value(ctx, value)
  File "/Users/dev/Library/Python/2.7/lib/python/site-packages/click/core.py", line 1344, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/Users/dev/Library/Python/2.7/lib/python/site-packages/click/core.py", line 1342, in _convert
    return self.type(value, self, ctx)
  File "/Users/dev/Library/Python/2.7/lib/python/site-packages/click/types.py", line 38, in __call__
    return self.convert(value, param, ctx)
  File "/Users/dev/Library/Python/2.7/lib/python/site-packages/click/types.py", line 159, in convert
    (value, ', '.join(self.choices)), param, ctx)
  File "/Users/dev/Library/Python/2.7/lib/python/site-packages/click/types.py", line 68, in fail
    raise BadParameter(message, ctx=ctx, param=param)
  File "/Users/dev/Library/Python/2.7/lib/python/site-packages/click/exceptions.py", line 71, in __init__
    UsageError.__init__(self, message, ctx)
  File "/Users/dev/Library/Python/2.7/lib/python/site-packages/click/exceptions.py", line 38, in __init__
    ClickException.__init__(self, message)
  File "/Users/dev/Library/Python/2.7/lib/python/site-packages/click/exceptions.py", line 14, in __init__
    message = message.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 16: ordinal not in range(128)```

**Comment by zoidbergwill** [comment]
Can you show the context in `File "/usr/local/bin/../lib/node_modules/@dporganizer/dpo-cli/scripts/deploy/python-helper/deploy.py"` around line 394? Maybe upload the full file if possible?

**Comment by BeyondEvil** [comment]
Here are the lines I think are relevant @zoidbergwill, let me know if you need more!

https://gist.github.com/BeyondEvil/de2cb21acae364e92275a046314cc34d
