### ISSUE TITLE
show_default=True and multiple multi-value options

### ISSUE THREAD

**Issue by phha** [pallets/click#913]
This crashes:

```python
@click.command()
@click.option('--name', default=[(1, 'World')], multiple=True, type=(int, str), show_default=True)
def hello(name):
    pass
```

```
Traceback (most recent call last):
  File "hello.py", line 8, in <module>
    hello()
  File "/home/phha8735/.local/share/virtualenvs/stash-gopMnmvH/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/phha8735/.local/share/virtualenvs/stash-gopMnmvH/lib/python3.5/site-packages/click/core.py", line 696, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/phha8735/.local/share/virtualenvs/stash-gopMnmvH/lib/python3.5/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/home/phha8735/.local/share/virtualenvs/stash-gopMnmvH/lib/python3.5/site-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/phha8735/.local/share/virtualenvs/stash-gopMnmvH/lib/python3.5/site-packages/click/core.py", line 1404, in handle_parse_result
    self.callback, ctx, self, value)
  File "/home/phha8735/.local/share/virtualenvs/stash-gopMnmvH/lib/python3.5/site-packages/click/core.py", line 78, in invoke_param_callback
    return callback(ctx, param, value)
  File "/home/phha8735/.local/share/virtualenvs/stash-gopMnmvH/lib/python3.5/site-packages/click/core.py", line 809, in show_help
    echo(ctx.get_help(), color=ctx.color)
  File "/home/phha8735/.local/share/virtualenvs/stash-gopMnmvH/lib/python3.5/site-packages/click/core.py", line 496, in get_help
    return self.command.get_help(self)
  File "/home/phha8735/.local/share/virtualenvs/stash-gopMnmvH/lib/python3.5/site-packages/click/core.py", line 830, in get_help
    self.format_help(ctx, formatter)
  File "/home/phha8735/.local/share/virtualenvs/stash-gopMnmvH/lib/python3.5/site-packages/click/core.py", line 845, in format_help
    self.format_options(ctx, formatter)
  File "/home/phha8735/.local/share/virtualenvs/stash-gopMnmvH/lib/python3.5/site-packages/click/core.py", line 859, in format_options
    rv = param.get_help_record(ctx)
  File "/home/phha8735/.local/share/virtualenvs/stash-gopMnmvH/lib/python3.5/site-packages/click/core.py", line 1617, in get_help_record
    if isinstance(self.default, (list, tuple))
  File "/home/phha8735/.local/share/virtualenvs/stash-gopMnmvH/lib/python3.5/site-packages/click/core.py", line 1616, in <genexpr>
    ', '.join('%s' % d for d in self.default)
TypeError: not all arguments converted during string formatting
```

It seems to be related to using a combination of tuple types, mutlitple=True and show_default=True.

**Comment by kporangehat** [comment]
I'm unable to reproduce this on Python `v3.6.5` or `v3.5.5` using Click `v[5.0, 6.0, ..., 6.7, master]`.

If you're still experiencing the issue, please re-open an issue and  provide some additional version information, OS, and a full example which reproduces the problem.
