### ISSUE TITLE
The `errors` argument in `click.open_file` is ignored on python3

### ISSUE THREAD

**Issue by ei-grad** [pallets/click#958]
The `errors` argument of `click.open_file` is not propagated to `sys.stdin` on python 3.x if there is no `encoding` argument in couple with `errors`.

How to reproduce:

```bash
> head -c64 /dev/urandom | python3 -c 'import click
print(click.open_file("-", errors="ignore").read())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 1: invalid continuation byte
```

It is because `_force_correct_text_reader` function checks that `_stream_is_misconfigured(text_reader)` call returns `False` and returns the `text_reader` as is.

**Comment by ei-grad** [comment]
Oh. Found that it also doesn't work for regular files:

```> head -c64 /dev/urandom > random.bin
python3 -c 'import click
print(click.open_file("random.bin", errors="ignore").read())'
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 0: invalid start byte
```

**Comment by dawran6** [comment]
Hi @ei-grad , would you submit a PR? Thanks!

**Comment by dougharris** [comment]
Note: probably relevant: http://click.pocoo.org/5/python3/

**Comment by joewledger** [comment]
Taking a look into this.

**Comment by joewledger** [comment]
Work-in-progress PR for this issue: https://github.com/pallets/click/pull/1298
