### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'expandtabs'

### ISSUE THREAD

**Issue by BeyondEvil** [pallets/click#972]
```
Traceback (most recent call last):
  File "/usr/local/bin/../lib/node_modules/@dporganizer/dpo-cli/scripts/dev-env/python-helper/dev-env.py", line 665, in <module>
    @click.pass_context
  File "/root/.local/lib/python3.6/site-packages/click/decorators.py", line 168, in decorator
    attrs['help'] = inspect.cleandoc(attrs['help'])
  File "/usr/local/lib/python3.6/inspect.py", line 617, in cleandoc
    lines = doc.expandtabs().split('\n')
AttributeError: 'tuple' object has no attribute 'expandtabs'
```

This happens with python 3.6 and latest click (6.7? eg. `pip install click`)

**Comment by BeyondEvil** [comment]
Issue was a syntactically valid comma. But it turned a list into a tuple and made inspect choke.
