### ISSUE TITLE
nargs and int incompatibility for 'click.argument'

### ISSUE THREAD

**Issue by stephenfin** [pallets/click#982]
Take the following minimal example:

```python
import click

@click.command()
@click.argument('patch_ids', type=click.INT, nargs='+')
def hello(patch_ids):
    click.echo('Received: %r' % list(patch_ids))


if __name__ == '__main__':
    hello()
```

# Expected result

```bash
$ python main.py 123 456
Received: [123, 456]
```

# Actual result

```bash
$ python main.py 123 456
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    hello()
  File "/tmp/test-click/venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/test-click/venv/lib/python2.7/site-packages/click/core.py", line 696, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/tmp/test-click/venv/lib/python2.7/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/tmp/test-click/venv/lib/python2.7/site-packages/click/core.py", line 876, in parse_args
    opts, args, param_order = parser.parse_args(args=args)
  File "/tmp/test-click/venv/lib/python2.7/site-packages/click/parser.py", line 268, in parse_args
    self._process_args_for_args(state)
  File "/tmp/test-click/venv/lib/python2.7/site-packages/click/parser.py", line 276, in _process_args_for_args
    [x.nargs for x in self._args])
  File "/tmp/test-click/venv/lib/python2.7/site-packages/click/parser.py", line 53, in _unpack_args
    x = [_fetch(args) for _ in range(nargs)]
TypeError: range() integer end argument expected, got str.
```

# Additional information

Package versions below.

```bash
$ python --version
Python 2.7.14
$ pip freeze
click==6.7
```

This also happens on the latest master commit (61494320c58f1f24612183e281d5cc11ac12d44e).

```bash
$ pip install git+https://github.com/pallets/click.git
...
$ pip freeze
click==7.0.dev0
$ python main.py 123 456
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    hello()
  ...
```

**Comment by stephenfin** [comment]
Oops, my mistake. It seems `nargs='+'` is not supported. Instead I should have used the combination of `nargs=-1` and `required=True`.

```python
import click

@click.command()
@click.argument('patch_ids', type=click.INT, nargs=-1, required=True)
def hello(patch_ids):
    click.echo('Hello World!')
    click.echo('Received: %r' % list(patch_ids))


if __name__ == '__main__':
    hello()
```

Sorry for the noise.
